# This is a basic workflow to help you get started with Actions

name: Generate ERD

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: wakeup mysql
        run: |
          docker run -d --rm --name mysql -p 3306:3306 -e MYSQL_DATABASE=testdb -e MYSQL_ROOT_PASSWORD=password mysql:5.7.34

      - name: initialize database
        run: |
          mysql -uroot -ppassword testdb < ../sql/02_create_table.sql

      # Runs a set of commands using the runners shell
      - name: Generate ERD
        run: |
          mkdir docker/schemaspy
          cd docker
          docker run -d --rm --name schemaspy -v ./schemaspy:/output schemaspy/schemaspy "java -jar schemaspy.jar -db testdb -t mysql -host db -port 3306 -s testdb -u root -p password"
